name: GitHub Actions pipeline for AWS multi-region demo
on:
  push:
    branches:
    - main
jobs:
  opentofu:
    runs-on: ubuntu-latest
    steps:
    - name: OpenTofu - Setup Tofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: ^1.7.0
    - name: Checkout
      uses: actions/checkout@v3
    - name: Initialize OpenTofu without backend
      run: |
        tofu init -backend=false
        tofu -chdir="multi-region-demo/" init -backend=false
    - name: Check OpenTofu formatting
      run: |
        tofu fmt -check
        tofu -chdir="multi-region-demo/" fmt -check
    - name: Validate OpenTofu configuration
      run: |
        tofu validate
        tofu -chdir="multi-region-demo/" validate
